// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Schema engine (migrate / db push / db pull / introspect) uses this URL.
    // Must be the SESSION-mode pooler (5432); the transaction pooler (6543)
    // cannot run migrations. Runtime queries use DATABASE_URL via the app's
    // driver adapter, configured in application code — not here.
    url: process.env["DIRECT_URL"],
  },
});
